### ISSUE TITLE
How do you get all revisions of a document?

### ISSUE THREAD

**Issue by timothytierney** [ArangoDB-Community/pyArango#106]
Using the fetchDocument API from Collections and want to have it return all the revisions (_rev) of the said document.  Is this possible?  There is a 'rev' parameter, but that is looking for a specific revision string and if I can't get all the _rev strings, I don't know what this value is.

If I use the "queries" tab in ArangoDB UI and use the following query of a document with multiple revisions it displays all the revisions:

For u in collectionX
    filter  u.name=="xxx"
    return u

Thanks in advance.

**Comment by tariqdaouda** [comment]
Hi, 

There's no history of revisions, _rev simply changes when you change the document. This allows you to know when a change has been applied and recache the document if needed.

**Comment by dothebart** [comment]
ArangoDB itself doesn't support accessing multiple versions of a document. Thus, `_rev` can be only use to see whether a document has meanwhile been changed, not to get older revisions.

Closing this as unsupported.
