### ISSUE TITLE
Need to convert pyArango.document.Document into a Dataframe

### ISSUE THREAD

**Issue by eadka** [ArangoDB-Community/pyArango#134]
Hi, I need to convert the contents of an Arango collection, which is a pyArango.document.Document object into a pandas dataframe. How can this be done? Here is the code i'm using:

`from pyArango.connection import *`

   
    
`
def arango_connect(conn_url,dbname,collname):`
              
    conn = Connection(arangoURL = conn_url)
    d_server = conn[dbname]  #["raw-data"]
    aql = "FOR x IN " + collname + " RETURN x._key"
    queryResult = d_server.AQLQuery(aql, rawResults=True, batchSize=1000)
    col_key = np.zeros((len(queryResult)))
    ind = 0
    
    ## extracting the keys
    for key in queryResult:
        col_key[ind] = key
        ind +=1
    
    #converting this to str
    col_key = (col_key.astype(np.int)).astype(np.str)
    return d_server[collname],col_key`

`conn_url = 'http://xx.xxx.xx.x:xxxx'
dbname = 'xxx'
collname = 'xxx'`

`Collection, col_key = arango_connect(conn_url,dbname,collname`

The collection is returned in the **Collection** parameter but need to extract individual records from it.

**Comment by tariqdaouda** [comment]
Hi, if you set rawResults = True, you should get a dictionary that you can then transform into json and load into pandas using this panda's [read_json](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html) function.

**Comment by eadka** [comment]
Thank you @tariqdaouda

**Comment by eadka** [comment]
Updated my code to:

`def read_collection(conn_url, dbname,collname):`

    conn = Connection(arangoURL = conn_url)
    d_server = conn[dbname]  #["raw-data"]
    aql = "FOR x IN " + collname + " RETURN x._key"
    
    queryResult = d_server.AQLQuery(aql, rawResults=True, batchSize=1000)
    col_key = np.zeros((len(queryResult)))
    ind = 0
           
    ## extracting the keys
    for key in queryResult:
        col_key[ind] = key
        ind +=1
   
    #converting this to str
    col_key = (col_key.astype(np.int)).astype(np.str)
    return d_server[collname],col_value, col_key
 
    ## extracting the Records
    aql_val = "FOR x IN " + collname + " RETURN x"
    valueResult = d_server.AQLQuery(aql_val, rawResults=True, batchSize=1000)
    col_value = {}
    ind_val = 0
    
    for value in valueResult :
        col_value[ind_val] = value
        ind_val +=1
`
conn_url = 'http://xx.xxx.xx.x:xxxx' 
dbname = 'xxx' 
collname = 'xxx'`

`Collection, Records, col_key = read_collection(conn_url,dbname,collname)`
