### ISSUE TITLE
gcc/gevent errors during pyArango installation

### ISSUE THREAD

**Issue by logan169** [ArangoDB-Community/pyArango#145]
Hi,

I've tried to install pyArango from the repo and had some errors that I've never seen before. It seems to be some gcc errors associated with gevent (see end of terminal log). 

I think this issue may be associated with last [commit](https://github.com/ArangoDB-Community/pyArango/commit/e09646dc54d9e7b7595971ce64a483ad458e98e4) in date as I didn't had this issue 2 days ago while running the same operation.

Update: I've tried to do the same operation with dev branch whose last commit was 29days ago and got same issue so its not related to the last commit but to gevent it self.

Here is a complet terminal output for the operation:

<pre><font color="#8AE234"><b>master</b></font>:<font color="#729FCF"><b>~/Documents/test/pyArango</b></font>$ python setup.py develop
running develop
running egg_info
writing pyArango.egg-info/PKG-INFO
writing dependency_links to pyArango.egg-info/dependency_links.txt
writing entry points to pyArango.egg-info/entry_points.txt
writing requirements to pyArango.egg-info/requires.txt
writing top-level names to pyArango.egg-info/top_level.txt
reading manifest file &apos;pyArango.egg-info/SOURCES.txt&apos;
reading manifest template &apos;MANIFEST.in&apos;
writing manifest file &apos;pyArango.egg-info/SOURCES.txt&apos;
running build_ext
Creating /home/master/miniconda3/envs/bluwr/lib/python3.7/site-packages/pyArango.egg-link (link to .)
pyArango 1.3.3 is already the active version in easy-install.pth
Installing sample script to /home/master/miniconda3/envs/bluwr/bin

Installed /home/master/Documents/test/pyArango
Processing dependencies for pyArango==1.3.3
Searching for gevent
Reading https://pypi.org/simple/gevent/
Downloading https://files.pythonhosted.org/packages/53/4a/076bd8c6d3328381bdec816ba7f078276dd4618eb2fe289bec172779d5ff/gevent-1.5a1.tar.gz#sha256=1141c62acee22328436cb09a7e1bcc6f652e88cf913d5de1066b38b6af7e221d
Best match: gevent 1.5a1
Processing gevent-1.5a1.tar.gz
Writing /tmp/easy_install-c77ctjiz/gevent-1.5a1/setup.cfg
Running gevent-1.5a1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-c77ctjiz/gevent-1.5a1/egg-dist-tmp-0g1r_rj4
/home/master/miniconda3/envs/bluwr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: &apos;cffi_modules&apos;
  warnings.warn(msg)
warning: no files found matching &apos;changelog.rst&apos;
warning: no files found matching &apos;Makefile.ext&apos;
warning: no files found matching &apos;known_failures.py&apos;
warning: no files found matching &apos;.pep8&apos;
no previously-included directories found matching &apos;*/__pycache__&apos;
warning: no previously-included files matching &apos;*.so&apos; found anywhere in distribution
warning: no previously-included files matching &apos;*.o&apos; found anywhere in distribution
warning: no previously-included files matching &apos;*.lo&apos; found anywhere in distribution
warning: no previously-included files matching &apos;*.la&apos; found anywhere in distribution
warning: no previously-included files matching &apos;.dirstamp&apos; found anywhere in distribution
warning: no previously-included files matching &apos;config.log&apos; found anywhere in distribution
warning: no previously-included files matching &apos;config.status&apos; found anywhere in distribution
warning: no previously-included files matching &apos;config.cache&apos; found anywhere in distribution
no previously-included directories found matching &apos;docs/_build&apos;
warning: no previously-included files matching &apos;*.pyc&apos; found anywhere in distribution
warning: no previously-included files matching &apos;.coverage&apos; found under directory &apos;src/greentest&apos;
no previously-included directories found matching &apos;src/greentest/htmlcov&apos;
warning: no previously-included files matching &apos;stamp-h?&apos; found under directory &apos;deps/c-ares&apos;
warning: no previously-included files matching &apos;ares_build.h.orig&apos; found under directory &apos;deps/c-ares&apos;
warning: no previously-included files matching &apos;_corecffi.c&apos; found under directory &apos;src/gevent&apos;
warning: no previously-included files found matching &apos;configure-output&apos;
warning: no previously-included files found matching &apos;configure-output.txt&apos;
warning: no previously-included files found matching &apos;deps/TAGS&apos;
warning: no previously-included files found matching &apos;deps/c-ares/ares_build.h&apos;
warning: no previously-included files found matching &apos;deps/c-ares/ares_config.h&apos;
warning: no previously-included files found matching &apos;deps/c-ares/libcares.pc&apos;
warning: no previously-included files found matching &apos;deps/c-ares/libtool&apos;
warning: no previously-included files found matching &apos;deps/c-ares/Makefile&apos;
no previously-included directories found matching &apos;deps/c-ares/.deps&apos;
no previously-included directories found matching &apos;deps/c-ares/.libs&apos;
no previously-included directories found matching &apos;deps/libev/.deps&apos;
no previously-included directories found matching &apos;deps/libev/.libs&apos;
warning: no previously-included files matching &apos;Makefile&apos; found under directory &apos;deps/libev&apos;
warning: no previously-included files matching &apos;libtool&apos; found under directory &apos;deps/libev&apos;
warning: no previously-included files matching &apos;stamp-h?&apos; found under directory &apos;deps/libev&apos;
warning: no previously-included files matching &apos;config.h&apos; found under directory &apos;deps/libev&apos;
no previously-included directories found matching &apos;deps/libuv/.deps&apos;
no previously-included directories found matching &apos;deps/libuv/.libs&apos;
no previously-included directories found matching &apos;deps/libuv/src/.deps&apos;
no previously-included directories found matching &apos;deps/libuv/src/unix/.deps&apos;
no previously-included directories found matching &apos;deps/libuv/src/win/.deps&apos;
no previously-included directories found matching &apos;deps/libuv/test/.deps&apos;
no previously-included directories found matching &apos;deps/libuv/autom4te.cache&apos;
no previously-included directories found matching &apos;deps/libuv/m4&apos;
warning: no previously-included files matching &apos;Makefile&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;Makefile.in&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;ar-lib&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;aclocal.m4&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;compile&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;configure&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;depcomp&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;install-sh&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;libtool&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;libuv.pc&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;ltmain.sh&apos; found under directory &apos;deps/libuv&apos;
warning: no previously-included files matching &apos;missing&apos; found under directory &apos;deps/libuv&apos;
Running &apos;(cd  &quot;/tmp/easy_install-c77ctjiz/gevent-1.5a1/deps/libev&quot;  &amp;&amp; sh ./configure -C &gt; configure-output.txt )&apos; in /tmp/easy_install-c77ctjiz/gevent-1.5a1
Embedding c-ares &lt;_setuputils.ConfiguringBuildExt object at 0x7f7111ae4e10&gt; &lt;_setuputils.Extension(&apos;gevent.resolver.cares&apos;) at 0x7f7111b37358&gt;
Inserted  build/temp.linux-x86_64-3.7/c-ares in include dirs [&apos;build/temp.linux-x86_64-3.7/c-ares&apos;, &apos;src/gevent/resolver&apos;, &apos;/tmp/easy_install-c77ctjiz/gevent-1.5a1/deps/c-ares&apos;]
Running &apos;(cd  &quot;/tmp/easy_install-c77ctjiz/gevent-1.5a1/deps/c-ares&quot;  &amp;&amp; if [ -r ares_build.h ]; then cp ares_build.h ares_build.h.orig; fi   &amp;&amp; sh ./configure --disable-dependency-tracking -C CONFIG_COMMANDS=   &amp;&amp; cp ares_config.h ares_build.h &quot;$OLDPWD&quot;   &amp;&amp; cat ares_build.h   &amp;&amp; if [ -r ares_build.h.orig ]; then mv ares_build.h.orig ares_build.h; fi) &gt; configure-output.txt&apos; in /tmp/easy_install-c77ctjiz/gevent-1.5a1/build/temp.linux-x86_64-3.7/c-ares
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/_greenlet_primitives.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/greenlet.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/_hub_primitives.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/_tracer.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/_hub_local.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/_waiter.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/local.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/_semaphore.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/_abstract_linkable.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/_ident.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/_imap.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/event.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/queue.c: Aucun fichier ou dossier de ce type
<b>gcc:</b> <font color="#EF2929"><b>error: </b></font>src/gevent/libev/corecext.c: Aucun fichier ou dossier de ce type
error: Setup script exited with error: command &apos;gcc&apos; failed with exit status 1
</pre>

Cheers.

**Comment by logan169** [comment]
I know the issue is maybe more specific to gevent installation, but just wanted to flag it out as well as it seems to be new.

**Comment by tariqdaouda** [comment]
Thanks for bringing that up.
Gevent doesn't play well with different versions of python and breaks some parts of python's native MP module. Removed it as hard dependency, and reverted back to requests as the default (on the dev branch for now). Users can install it if they wish to use it.
