### ISSUE TITLE
Some documentation pages are missing

### ISSUE THREAD

**Issue by aernesto** [ArangoDB-Community/pyArango#146]
The following documentation pages are empty:
- [Connection](https://pyarango.readthedocs.io/en/latest/connection/)
- [Database](https://pyarango.readthedocs.io/en/latest/database/)

**Comment by tariqdaouda** [comment]
We've been experiencing, on and off problems with readthedocs since the beginning. If anyone has a solution to this problem please reach out.

**Comment by aernesto** [comment]
I see. Feel free to close the issue then; it has been[ forwarded to readthedocs](https://github.com/rtfd/readthedocs.org/issues/5736).
Note that the missing documentation pages seem to be correct now, and the bug hasn't been replicated (yet).

**Comment by aernesto** [comment]
@tariqdaouda Just sharing with you[ this post](https://github.com/rtfd/readthedocs.org/issues/5736#issuecomment-496255808), in case it is useful and you hadn't seen it.

**Comment by dothebart** [comment]
Closing as solved.
