### ISSUE TITLE
Best way to check if collection exists

### ISSUE THREAD

**Issue by igaln** [ArangoDB-Community/pyArango#162]
Trying to check if a collection exists before creating

Options

- Creating a collection, catching error if it already exists
- Parsing over db.collections, and matching name/key

These seems to an isCollection in Collection object, but I assumed that is for initialized collections already.

Please advice,
Thank you

**Comment by subfxnet** [comment]
in `pyArango/database.py` there is a method `Database().hasCollection(name): bool`.  You could also call `Database().reloadCollections()` first to ensure you have the latest collection set loaded into the client.

Something like:
```
from pyArango.connection import Connection
from pyArango.collection import Collection

conn = Connection(**params)
sess = conn[DB_NAME]
sess.reloadCollections()
if sess.hasCollection(name):
    return sess.collections[name]
return sess.createCollection(name)
```

**Comment by tariqdaouda** [comment]
As @subfxnet  pointed out you could use the *hasCollection(<name>)* function. You could also just do a try/except:

```
try:
  DB[col_name]
except KeyError:
  print("collection not found")
```
