### ISSUE TITLE
Collections.bulkImport_json() won't accept JSON objects

### ISSUE THREAD

**Issue by AndrewFalanga** [ArangoDB-Community/pyArango#188]
When trying to use the function `Collections.bulkImport_json` to upload a JSON structure built from **pytest-json-report**, I continually receive

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.8/site-packages/pyArango/collection.py", line 777, in bulkImport_json
> TypeError: string indices must be integers

Why is this?  It matters not how I attempt to reformat the JSON data, I still see this error.  The JSON itself is properly formatted because the following works just fine:

```
import json
data = json.load(open('/path/to/json'))
```

**Comment by wmullen0** [comment]
I am also seeing the same issue. Curious if you had the solution.

**Comment by AndrewFalanga** [comment]
I didn't and as a group, my work colleagues, we've moved to MongoDB over ArangoDB.
