### ISSUE TITLE
We need the pyArango client to support both database versions v2.8.9 and v3.

### ISSUE THREAD

**Issue by ntwrick** [ArangoDB-Community/pyArango#38]
We are still using ArangoDB v2.8.9 and a conversion to v3 cannot be scheduled soon.

Note that the arangojs client (https://github.com/arangodb/arangojs) currently allows the selection of the DB version via an arangoVersion property. It would be most helpful if pyArango could do the same.

var db = new arangojs.Database({url: arangoUrl, arangoVersion: 20800});

We would appreciate any help on making this a priority.

Thanks,

Rick

**Comment by tariqdaouda** [comment]
Hi Rick,

I have created a new branch to centralize the backward compatibility developments.
You can give it a try here: https://github.com/tariqdaouda/pyArango/tree/28backcomp
You should be able to select the desired version by doing :

`conn = Connection(version="2.8.x")
`

However It is still in development, and In the meantime you can still use this older version of the driver: https://github.com/tariqdaouda/pyArango/tree/ArangoDBV2

Cheers,

**Comment by brennv** [comment]
I looked into automating tests for pre-v3 environments with #41 but no luck yet.

**Comment by dothebart** [comment]
Since upstream support for 2.8 is no more and pyArango safely works with the current version 3.4 I will close this issue.
